version: '3.9'

services:
  nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/var/www:ro
      - phpsocket:/phpsocket
    networks:
      - the-network
    ports:
      - '8080:8080'

  php:
    build:
      context: ./php
    working_dir: '/var/www/html'
    volumes:
      - ./php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ./www:/var/www:ro
      - phpsocket:/phpsocket
    networks:
      - the-network

networks:
  the-network:
    driver: bridge

volumes:
  phpsocket:
